name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install --legacy-peer-deps
        working-directory: ./mp2
      - name: Run Prettier
        run: npm run prettier
        working-directory: ./mp2

  build_and_deploy:
    runs-on: ubuntu-latest
    needs: prettier
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
        working-directory: ./mp2
      - name: Build project
        run: npm run build
        working-directory: ./mp2
      - name: Check if build exists
        run: ls -la ./mp2/build
      - name: Install Netlify CLI
        run: npm install -g netlify-cli
      - name: Deploy to Netlify
        run: npx netlify-cli deploy --site ${{ secrets.NETLIFY_SITE_ID }} --auth ${{ secrets.NETLIFY_AUTH_TOKEN }} --prod --dir ./build
